### CI action that runs tests written in Gut. Please make sure you generate a `.gutconfig.json` file first!

name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Download Godot and run tests
        run: |
          cd source
          wget "https://downloads.tuxfamily.org/godotengine/3.3.3/Godot_v3.3.3-stable_linux_headless.64.zip"
          unzip Godot_v3.3.3-stable_linux_headless.64.zip
          chmod +x Godot_v3.3.3-stable_linux_headless.64
          ./Godot_v3.3.3-stable_linux_headless.64 -s addons/gut/gut_cmdln.gd --path .
